services:
  redis:
    image: docker-registry-002.zeuslearning.com/zeuslearning/redis
    container_name: redis_container
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
    volumes:
      - redis-data:/data
  

  rabbitmq:
    image: docker-registry-002.zeuslearning.com/zeuslearning/rabbitmq:3.8.6-management
    container_name: rabbitmq-container
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RabbitMQ__UserName}
      RABBITMQ_DEFAULT_PASS: ${RabbitMQ__Password}
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "check_running"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    restart: unless-stopped

  mysql:
    image: docker-registry-002.zeuslearning.com/zeuslearning/mysql
    container_name: mysql-container
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "root"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - mysql-data:/var/lib/mysql
    restart: unless-stopped

  trainee-management-api-service:
    build:
      context: .
      dockerfile: ./TraineeManagement.Api/Dockerfile
      args:
        DOMAIN_OWNER: ${DOMAIN_OWNER}
        NUGET_REPO_NAME: ${NUGET_REPO_NAME}
        CODEARTIFACT_AUTH_TOKEN: ${CODEARTIFACT_AUTH_TOKEN}
        REGION: ${REGION}
    env_file:
      - ./TraineeManagement.Api/.env
    container_name: trainee-api-container
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health/live"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    depends_on:
      mysql:
        condition: service_started
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_started
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    restart: on-failure
 
  submission-worker-service:
    build:
      context: .
      dockerfile: ./SubmissionProcessor.Worker/Dockerfile
      args:
        DOMAIN_OWNER: ${DOMAIN_OWNER}
        NUGET_REPO_NAME: ${NUGET_REPO_NAME}
        CODEARTIFACT_AUTH_TOKEN: ${CODEARTIFACT_AUTH_TOKEN}
        REGION: ${REGION}
    env_file:
      - ./SubmissionProcessor.Worker/.env
    container_name: submission-worker-container
    depends_on:
      mysql:
        condition: service_started
      rabbitmq:
        condition: service_healthy
      trainee-dir-service:
        condition: service_started
    ports:
      - "8081:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    restart: on-failure

  trainee-dir-service:
    build:
      context: .
      dockerfile: ./TraineeDirectory.Api/Dockerfile
      args:
        DOMAIN_OWNER: ${DOMAIN_OWNER}
        NUGET_REPO_NAME: ${NUGET_REPO_NAME}
        CODEARTIFACT_AUTH_TOKEN: ${CODEARTIFACT_AUTH_TOKEN}
        REGION: ${REGION}
    # env_file:
    #   - ./TraineeDirectory.Api/.env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health/live"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    container_name: traineedir-api-container
    ports:
      - "8082:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    restart: on-failure


volumes:
  redis-data:
  mysql-data:
  rabbitmq-data: